[general]
	editor="$EDITOR"
	confirmation=true
	mouse-support=false
	date-format="2006-01-02 15:04"
	date-tody-format="15:04"
	date-relative=14
	max-width=0
	list-placement="top"
	list-split="column"
	list-proportion=1
	content-proportion=2
	notifications-to-hide=[]
	quote-reply=false
	show-icons=true
	short-hints=false
	show-filter-phrase=true
	show-help=false
	stick-to-top=false
	show-boosted-user=true
	commands-in-new-pane=true
	dynamic-timeline-name=true
	terminal-title=1
	redraw-ui=true
	leader-key=","
	leader-timeout=1500

[[general.timelines]]
	name="🏡"
	type="home"
	hide-boosts=false
	hide-replies=false
 
[[general.timelines]]
	name="🔔"
	type="notifications"
	keys=["n"]

[[general.timelines]]
	name="🔖"
	type="bookmarks"
	keys=["B"]
	closed=false

[[general.timelines]]
	name="#linuxmint"
	type="tag"
	data="linuxmint"
	keys=["1"]

[[general.timelines]]
	name="#xfce"
	type="tag"
	data="xfce"
	keys=["2"]

[[general.timelines]]
	name="#tut"
	type="tag"
	data="tut"
	keys=["3"]

[[general.timelines]]
	name="#geoguessr"
	type="tag"
	data="geoguessr"
	keys=["4"]

[[general.leader-actions]]
	type="close-pane"
	shortcut="q"

[[general.leader-actions]]
	type="clear-notifications"
	shortcut="cn"

[media]
	delete-temp-files=false

[media.image]
	program="sxiv"
	args="-g 1200x800+100+100"
	terminal=false
	single=true
	reverse=false

[media.video]
	program="mpv"
	args=""
	terminal=false
	single=true
	reverse=false

[media.audio]
	program="mpv"
	args=""
	terminal=false
	single=true
	reverse=false

[media.link]
	program="brave-browser"
	terminal=false

[desktop-notification]
	followers=true
	favorite=true
	mention=true
	update=true
	boost=true
	poll=true
	posts=false

[open-custom]
# [[open-custom.programs]]
# The program to open the file with.
# default=""
# program=""

# Arguments to pass to the program.
# default=""
# args=""

# If the program runs in the terminal set this to true.
# default=false
# terminal=false

# What should the key hint in tut be for this program. See under the input
# section to learn more about hint.
# default=""
# hint=""

# A list of keys to to open files with this program. See under the input section
# to learn more about keys.
# default=[]
# keys=[]

# A list of special-keys to open files with this program. See under the input
# section to learn more about special-keys.
# default=[]
# special-keys=[]

[open-pattern]
# [[open-pattern.programs]]
# Here you can set your own glob patterns for opening matching URLs in the
# program you want them to open up in. You could for example open Youtube videos
# in your video player instead of your default browser. To see the syntax for
# glob pattern you can follow this URL https://github.com/gobwas/glob#syntax.
# default=""
# matching=""

[[open-pattern.programs]]
matching="gemini:*"
program="amfora"
terminal=true

[[open-pattern.programs]]
matching="*youtu*"
program="mpv"
terminal=false

# The program to open the file with.
# default=""
# program=""

# Arguments to pass to the program.
# default=""
# args=""

# If the program runs in the terminal set this to true.
# default=false
# terminal=false

[style]
# All styles can be represented in their HEX value like #ffffff or with their
# name, so in this case white. The only special value is "default" which equals
# to transparent, so it will be the same color as your terminal.
# You can also use xrdb colors like this xrdb:color1 The program will use colors
# prefixed with an * first then look for URxvt or XTerm if it can't find any
# color prefixed with an asterisk. If you don't want tut to guess the prefix you
# can set the prefix yourself. If the xrdb color can't be found a preset color
# will be used. You'll have to set theme="none" for this to work.

# The theme to use. You can use some themes that comes bundled with tut. Check
# out the themes available on the URL below. If a theme is named nord.toml you
# just write theme="nord".
# 
# https://github.com/RasmusLindroth/tut/tree/master/config/themes
# 
# You can also create a theme file in your config directory e.g.
# ~/.config/tut/themes/foo.toml and then set theme=foo.
# 
# If you want to use your own theme but don't want to create a new file, set
# theme="none" and then you can create your own theme below.
# 
# default="default"
theme="toxdefault"

# The xrdb prefix used for colors in .Xresources.
# default="guess"
xrdb-prefix="XTERM"

# The background color used on most elements.
# default=""
# background=""

# The text color used on most of the text.
# default=""
# text=""

# The color to display subtle elements or subtle text. Like lines and help text.
# default=""
# subtle=""

# The color for errors or warnings
# default=""
# warning-text=""

# This color is used to display username.
# default=""
# text-special-one=""

# This color is used to display username and key hints.
# default=""
# text-special-two=""

# The color of the bar at the top
# default=""
# top-bar-background=""

# The color of the text in the bar at the top.
# default=""
# top-bar-text=""

# The color of the bar at the bottom
# default=""
# status-bar-background=""

# The color of the text in the bar at the bottom.
# default=""
# status-bar-text=""

# The color of the bar at the bottom in view mode.
# default=""
# status-bar-view-background=""

# The color of the text in the bar at the bottom in view mode.
# default=""
# status-bar-view-text=""

# The color of the text in the command bar at the bottom.
# default=""
# command-text=""

# Background of selected list items.
# default=""
# list-selected-background=""

# The text color of selected list items.
# default=""
# list-selected-text=""

# The background color of selected list items that are out of focus.
# default=""
# list-selected-inactive-background=""

# The text color of selected list items that are out of focus.
# default=""
# list-selected-inactive-text=""

# The main color of the text for key hints
# default=""
# controls-text=""

# The highlight color of for key hints
# default=""
# controls-highlight=""

# The background color in dropdowns and autocompletions
# default=""
# autocomplete-background=""

# The text color in dropdowns at autocompletions
# default=""
# autocomplete-text=""

# The background color for selected value in dropdowns and autocompletions
# default=""
# autocomplete-selected-background=""

# The text color for selected value in dropdowns and autocompletions
# default=""
# autocomplete-selected-text=""

# The background color on selected button and the text color of unselected
# buttons
# default=""
# button-color-one=""

# The text color on selected button and the background color of unselected
# buttons
# default=""
# button-color-two=""

# The background on named timelines.
# default=""
# timeline-name-background=""

# The text color on named timelines
# default=""
# timeline-name-text=""

[input]
# In this section you set the keys to be used in tut.
# 		
# The hint option lets you set which part of the hint that will be highlighted
# in tut. E.g. [F]avorite results in a highlighted F and the rest of the text is
# displayed normaly.
# Some of the options can be in two states, like favorites, so there you can set
# the hint-alt option to something like Un[F]avorite.
# 
# Examples:
# "[D]elete" = Delete with a highlighted D
# "Un[F]ollow" = UnFollow with a highlighted F
# "[Enter]" = Enter where everything is highlighted
# "Yan[K]" = YanK with a highlighted K
# 
# The keys option lets you define what key that should be pressed. This is
# limited to on character only and they are case sensetive.
# Example:
# keys=["j","J"]
# 
# You can also set special-keys and they're for keys like Escape and Enter. To
# find the names of special keys you have to go to the following site and look
# for "var KeyNames = map[Key]string{"
# 
# https://github.com/gdamore/tcell/blob/master/key.go

[input.global-down]
# Keys for moving down

# default=["j", "J"]
keys=["j","J"]

# default=["Down"]
special-keys=["Down"]

[input.global-up]
# Keys for moving down

# default=["k", "K"]
keys=["k","K"]

# default=["Up"]
special-keys=["Up"]

[input.global-enter]
# To select items

# default=["Enter"]
special-keys=["Enter"]

[input.global-back]
	hint="[Esc]"
	special-keys=["Esc"]
[input.global-exit]
	hint="[Q]uit"
	keys=["q"]
[input.main-home]
	special-keys=["Home"]
[input.main-end]
	keys=["g"]
[input.main-prev-feed]
	special-keys=["Delete"]
[input.main-next-feed]
	special-keys=["End"]
[input.main-prev-pane]
	special-keys=["Left"]
[input.main-next-pane]
	special-keys=["Right"]
[input.main-next-account]
# Focus on the next account

# default=["Ctrl-N"]
special-keys=["Ctrl-N"]

[input.main-prev-account]
# Focus on the previous account

# default=["Ctrl-P"]
special-keys=["Ctrl-P"]

[input.main-compose]
# Compose a new toot

# default=["c", "C"]
keys=["c","C"]

[input.status-avatar]
# Open avatar

# default="[A]vatar"
hint="[A]vatar"

# default=["a", "A"]
keys=["a","A"]

[input.status-boost]
# Boost a toot

# default="[B]oost"
hint="[b]oost"

# default=["b", "B"]
keys=["b","B"]

[input.status-edit]
# Edit a toot

# default="[E]dit"
hint="[E]dit"

# default=["e", "E"]
keys=["e","E"]

[input.status-delete]
# Delete a toot

# default="[D]elete"
hint="[D]elete"

# default=["d", "D"]
keys=["d","D"]

[input.status-favorite]
# Favorite a toot

# default="[F]avorite"
hint="[F]avorite"

# default=["f", "F"]
keys=["f","F"]

[input.status-media]
# Open toots media files

# default="[M]edia"
hint="[M]edia"

# default=["m", "M"]
keys=["m","M"]

[input.status-links]
# Open links

# default="[O]pen"
hint="[O]pen"

# default=["o", "O"]
keys=["o","O"]

[input.status-poll]
# Open poll

# default="[P]oll"
hint="[P]oll"

# default=["p", "P"]
keys=["p","P"]

[input.status-reply]
# Reply to toot

# default="[R]eply"
hint="[R]eply"

# default=["r", "R"]
keys=["r","R"]

[input.status-bookmark]
# Save/bookmark a toot

# default="[S]ave"
hint="[S]ave"

# default="Un[S]ave"
hint-alt="Un[S]ave"

# default=["s", "S"]
keys=["s","S"]

[input.status-thread]
# View thread

# default="[T]hread"
hint="[T]hread"

# default=["t", "T"]
keys=["t","T"]

[input.status-user]
# Open user profile

# default="[U]ser"
hint="[U]ser"

# default=["u", "U"]
keys=["u","U"]

[input.status-view-focus]
# Open the view mode

# default="[V]iew"
hint="[V]iew"

# default=["v", "V"]
keys=["v","V"]

[input.status-yank]
# Yank the url of the toot

# default="[Y]ank"
hint="[Y]ank"

# default=["y", "Y"]
keys=["y","Y"]

[input.status-toggle-cw]
# Show the content in a content warning

# default="Press [Z] to toggle cw"
hint="Press [Z] to toggle cw"

# default=["z", "Z"]
keys=["z","Z"]

[input.status-show-filtered]
# Show the content of a filtered toot

# default="Press [Z] to view filtered toot"
hint="Press [Z] to view filtered toot"

# default=["z", "Z"]
keys=["z","Z"]

[input.user-avatar]
# View avatar

# default="[A]vatar"
hint="[A]vatar"

# default=["a", "A"]
keys=["a","A"]

[input.user-block]
# Block the user

# default="[B]lock"
hint="[B]lock"

# default="Un[B]lock"
hint-alt="Un[B]lock"

# default=["b", "B"]
keys=["b","B"]

[input.user-follow]
# Follow user

# default="[F]ollow"
hint="[F]ollow"

# default="Un[F]ollow"
hint-alt="Un[F]ollow"

# default=["f", "F"]
keys=["f","F"]

[input.user-follow-request-decide]
# Follow user

# default="Follow [R]equest"
hint="Follow [R]equest"

# default="Follow [R]equest"
hint-alt="Follow [R]equest"

# default=["r", "R"]
keys=["r","R"]

[input.user-mute]
# Mute user

# default="[M]ute"
hint="[M]ute"

# default="Un[M]ute"
hint-alt="Un[M]ute"

# default=["m", "M"]
keys=["m","M"]

[input.user-links]
# Open links

# default="[O]pen"
hint="[O]pen"

# default=["o", "O"]
keys=["o","O"]

[input.user-user]
# View user profile

# default="[U]ser"
hint="[U]ser"

# default=["u", "U"]
keys=["u","U"]

[input.user-view-focus]
# Open view mode

# default="[V]iew"
hint="[V]iew"

# default=["v", "V"]
keys=["v","V"]

[input.user-yank]
# Yank the user URL

# default="[Y]ank"
hint="[Y]ank"

# default=["y", "Y"]
keys=["y","Y"]

[input.list-open-feed]
# Open list

# default="[O]pen"
hint="[O]pen"

# default=["o", "O"]
keys=["o","O"]

[input.list-user-list]
# List all users in a list

# default="[U]sers"
hint="[U]sers"

# default=["u", "U"]
keys=["u","U"]

[input.list-user-add]
# Add user to list

# default="[A]dd"
hint="[A]dd"

# default=["a", "A"]
keys=["a","A"]

[input.list-user-delete]
# Delete user from list

# default="[D]elete"
hint="[D]elete"

# default=["d", "D"]
keys=["d","D"]

[input.link-open]
# Open URL

# default="[O]pen"
hint="[O]pen"

# default=["o", "O"]
keys=["o","O"]

[input.link-yank]
# Yank the URL

# default="[Y]ank"
hint="[Y]ank"

# default=["y", "Y"]
keys=["y","Y"]

[input.tag-open-feed]
# Open tag feed

# default="[O]pen"
hint="[O]pen"

# default=["o", "O"]
keys=["o","O"]

[input.tag-follow]
# Toggle follow on tag

# default="[F]ollow"
hint="[F]ollow"

# default="Un[F]ollow"
hint-alt="Un[F]ollow"

# default=["f", "F"]
keys=["f","F"]

[input.compose-edit-cw]
# Edit content warning text on new toot

# default="[C]W text"
hint="[C]W text"

# default=["c", "C"]
keys=["c","C"]

[input.compose-edit-text]
# Edit the text on new toot

# default="[E]dit text"
hint="[E]dit text"

# default=["e", "E"]
keys=["e","E"]

[input.compose-include-quote]
# Include a quote when replying

# default="[I]nclude quote"
hint="[I]nclude quote"

# default=["i", "I"]
keys=["i","I"]

[input.compose-media-focus]
# Focus on adding media to toot

# default="[M]edia"
hint="[M]edia"

# default=["m", "M"]
keys=["m","M"]

[input.compose-post]
# Post the new toot

# default="[P]ost"
hint="[P]ost"

# default=["p", "P"]
keys=["p","P"]

[input.compose-toggle-content-warning]
# Toggle content warning on toot

# default="[T]oggle CW"
hint="[T]oggle CW"

# default=["t", "T"]
keys=["t","T"]

[input.compose-visibility]
# Edit the visibility on new toot

# default="[V]isibility"
hint="[V]isibility"

# default=["v", "V"]
keys=["v","V"]

[input.compose-language]
# Edit the language of a toot

# default="[L]ang"
hint="[L]ang"

# default=["l", "L"]
keys=["l","L"]

[input.compose-poll]
# Switch to creating a poll

# default="P[O]ll"
hint="P[O]ll"

# default=["o", "O"]
keys=["o","O"]

[input.media-delete]
# Delete media file

# default="[D]elete"
hint="[D]elete"

# default=["d", "D"]
keys=["d","D"]

[input.media-edit-desc]
# Edit the description on media file

# default="[E]dit desc"
hint="[E]dit desc"

# default=["e", "E"]
keys=["e","E"]

[input.media-add]
# Add a new media file

# default="[A]dd"
hint="[A]dd"

# default=["a", "A"]
keys=["a","A"]

[input.vote-vote]
# Vote on poll

# default="[V]ote"
hint="[V]ote"

# default=["v", "V"]
keys=["v","V"]

[input.vote-select]
# Select item to vote on

# default="[Enter] to select"
hint="[Enter] to select"

# default=["Enter"]
special-keys=["Enter"]

[input.poll-add]
# Add a new poll option

# default="[A]dd"
hint="[A]dd"

# default=["a", "A"]
keys=["a","A"]

[input.poll-edit]
# Edit a poll option

# default="[E]dit"
hint="[E]dit"

# default=["e", "E"]
keys=["e","E"]

[input.poll-delete]
# Delete a poll option

# default="[D]elete"
hint="[D]elete"

# default=["d", "D"]
keys=["d","D"]

[input.poll-multi-toggle]
# Toggle voting on multiple options

# default="Toggle [M]ultiple"
hint="Toggle [M]ultiple"

# default=["m", "M"]
keys=["m","M"]

[input.poll-expiration]
# Change the expiration of poll

# default="E[X]pires"
hint="E[X]pires"

# default=["x", "X"]
keys=["x","X"]

[input.preference-name]
# Change display name

# default="[N]ame"
hint="[N]ame"

# default=["n", "N"]
keys=["n","N"]

[input.preference-visibility]
# Change default visibility of toots

# default="[V]isibility"
hint="[V]isibility"

# default=["v", "V"]
keys=["v","V"]

[input.preference-bio]
# Change bio in profile

# default="[B]io"
hint="[B]io"

# default=["b", "B"]
keys=["b","B"]

[input.preference-save]
	hint="[S]ave"
	keys=["s","S"]

[input.preference-fields]
	hint="[F]ields"
	keys=["f","F"]

[input.preference-fields-add]
	hint="[A]dd"
	keys=["a","A"]

[input.preference-fields-edit]
	hint="[E]dit"
	keys=["e","E"]

[input.preference-fields-delete]
	hint="[D]elete"
	keys=["d","D"]

[input.editor-exit]
	hint="[Esc] when done"
	special-keys=["Esc"]